# This tracing policy monitors kprobes operations.
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "kprobes-observe"
  annotations:
    description: "Observe Kprobes operations"
spec:
  kprobes:
  # Kprobes /sys/kernel/debug/kprobes/enabled is set by default,
  # any update is suspicious since it could lead to disable kprobes.
  - call: "write_enabled_file_bool"
    syscall: false
    args:
    - index: 0
      type: "file"
    message: "Possible kprobe host modification that can lead to security evasion"
